# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_03designer实战.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LayoutDemo(object):
    def setupUi(self, LayoutDemo):
        LayoutDemo.setObjectName("LayoutDemo")
        LayoutDemo.resize(796, 433)
        self.centralwidget = QtWidgets.QWidget(LayoutDemo)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 110, 504, 94))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.double_spin_box_returns_min = QtWidgets.QDoubleSpinBox(self.widget)
        self.double_spin_box_returns_min.setObjectName("double_spin_box_returns_min")
        self.gridLayout.addWidget(self.double_spin_box_returns_min, 1, 0, 1, 1)
        self.double_spin_box_returns_max = QtWidgets.QDoubleSpinBox(self.widget)
        self.double_spin_box_returns_max.setObjectName("double_spin_box_returns_max")
        self.gridLayout.addWidget(self.double_spin_box_returns_max, 1, 1, 1, 1)
        self.double_spin_box_maxdrawdown_min = QtWidgets.QDoubleSpinBox(self.widget)
        self.double_spin_box_maxdrawdown_min.setObjectName("double_spin_box_maxdrawdown_min")
        self.gridLayout.addWidget(self.double_spin_box_maxdrawdown_min, 2, 0, 1, 1)
        self.double_spin_box_maxdrawdown_max = QtWidgets.QDoubleSpinBox(self.widget)
        self.double_spin_box_maxdrawdown_max.setObjectName("double_spin_box_maxdrawdown_max")
        self.gridLayout.addWidget(self.double_spin_box_maxdrawdown_max, 2, 1, 1, 1)
        self.double_spin_box_sharp_min = QtWidgets.QDoubleSpinBox(self.widget)
        self.double_spin_box_sharp_min.setObjectName("double_spin_box_sharp_min")
        self.gridLayout.addWidget(self.double_spin_box_sharp_min, 3, 0, 1, 1)
        self.double_spin_box_sharp_max = QtWidgets.QDoubleSpinBox(self.widget)
        self.double_spin_box_sharp_max.setObjectName("double_spin_box_sharp_max")
        self.gridLayout.addWidget(self.double_spin_box_sharp_max, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setEnabled(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        LayoutDemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LayoutDemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 23))
        self.menubar.setObjectName("menubar")
        LayoutDemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LayoutDemo)
        self.statusbar.setObjectName("statusbar")
        LayoutDemo.setStatusBar(self.statusbar)

        self.retranslateUi(LayoutDemo)
        QtCore.QMetaObject.connectSlotsByName(LayoutDemo)

    def retranslateUi(self, LayoutDemo):
        _translate = QtCore.QCoreApplication.translate
        LayoutDemo.setWindowTitle(_translate("LayoutDemo", "MainWindow"))
        self.label_6.setText(_translate("LayoutDemo", " "))
        self.label.setText(_translate("LayoutDemo", "收益"))
        self.label_2.setText(_translate("LayoutDemo", "最大回撤"))
        self.label_3.setText(_translate("LayoutDemo", "sharp比"))
        self.label_4.setText(_translate("LayoutDemo", "最小值"))
        self.label_5.setText(_translate("LayoutDemo", "最大值"))
        self.pushButton.setText(_translate("LayoutDemo", "开始"))

