# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_001简单通信.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 0, 781, 551))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.thisLabel = QtWidgets.QLabel(self.layoutWidget)
        self.thisLabel.setObjectName("thisLabel")
        self.horizontalLayout.addWidget(self.thisLabel)
        self.this_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.this_lineEdit.setObjectName("this_lineEdit")
        self.horizontalLayout.addWidget(self.this_lineEdit)
        self.thisButton = QtWidgets.QPushButton(self.layoutWidget)
        self.thisButton.setObjectName("thisButton")
        self.horizontalLayout.addWidget(self.thisButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.thatLabel = QtWidgets.QLabel(self.layoutWidget)
        self.thatLabel.setObjectName("thatLabel")
        self.horizontalLayout_2.addWidget(self.thatLabel)
        self.that_lineEdit2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.that_lineEdit2.setObjectName("that_lineEdit2")
        self.horizontalLayout_2.addWidget(self.that_lineEdit2)
        self.anotherButton = QtWidgets.QPushButton(self.layoutWidget)
        self.anotherButton.setObjectName("anotherButton")
        self.horizontalLayout_2.addWidget(self.anotherButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.thatIP = QtWidgets.QLabel(self.layoutWidget)
        self.thatIP.setObjectName("thatIP")
        self.horizontalLayout_3.addWidget(self.thatIP)
        self.that_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.that_lineEdit.setObjectName("that_lineEdit")
        self.horizontalLayout_3.addWidget(self.that_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.this_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.this_comboBox.setObjectName("this_comboBox")
        self.this_comboBox.addItem("")
        self.this_comboBox.addItem("")
        self.this_comboBox.addItem("")
        self.this_comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.this_comboBox)
        self.connectButton = QtWidgets.QPushButton(self.layoutWidget)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_4.addWidget(self.connectButton)
        self.disconnectButton = QtWidgets.QPushButton(self.layoutWidget)
        self.disconnectButton.setObjectName("disconnectButton")
        self.horizontalLayout_4.addWidget(self.disconnectButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.sendLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sendLabel.setFont(font)
        self.sendLabel.setObjectName("sendLabel")
        self.verticalLayout_3.addWidget(self.sendLabel)
        self.this_textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.this_textEdit.setObjectName("this_textEdit")
        self.verticalLayout_3.addWidget(self.this_textEdit)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sendButton = QtWidgets.QPushButton(self.layoutWidget)
        self.sendButton.setObjectName("sendButton")
        self.verticalLayout_2.addWidget(self.sendButton)
        self.exitButton = QtWidgets.QPushButton(self.layoutWidget)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout_2.addWidget(self.exitButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.receiveLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.receiveLabel.setFont(font)
        self.receiveLabel.setObjectName("receiveLabel")
        self.horizontalLayout_5.addWidget(self.receiveLabel)
        self.clearButton = QtWidgets.QPushButton(self.layoutWidget)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_5.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.that_textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.that_textEdit.setObjectName("that_textEdit")
        self.verticalLayout.addWidget(self.that_textEdit)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.thisButton.clicked.connect(self.this_lineEdit.clear)
        self.clearButton.clicked.connect(self.that_textEdit.clear)
        self.exitButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.thisLabel.setText(_translate("MainWindow", "本机IP"))
        self.thisButton.setText(_translate("MainWindow", "重新设置本机IP"))
        self.thatLabel.setText(_translate("MainWindow", "目标端口"))
        self.anotherButton.setText(_translate("MainWindow", "窗口多开"))
        self.thatIP.setText(_translate("MainWindow", "目标IP"))
        self.this_comboBox.setItemText(0, _translate("MainWindow", "TCP客户端"))
        self.this_comboBox.setItemText(1, _translate("MainWindow", "TCP服务端"))
        self.this_comboBox.setItemText(2, _translate("MainWindow", "UDP客户端"))
        self.this_comboBox.setItemText(3, _translate("MainWindow", "UDP服务端"))
        self.connectButton.setText(_translate("MainWindow", "连接网络"))
        self.disconnectButton.setText(_translate("MainWindow", "断开网络"))
        self.sendLabel.setText(_translate("MainWindow", "发送区域"))
        self.label.setText(_translate("MainWindow", "大国制作"))
        self.sendButton.setText(_translate("MainWindow", "发送消息"))
        self.exitButton.setText(_translate("MainWindow", "退出系统"))
        self.receiveLabel.setText(_translate("MainWindow", "接收区域"))
        self.clearButton.setText(_translate("MainWindow", "清除消息"))

