list = ['下压时间(Down press time*1S)', '堵进延时(Stock in delay*1S)', '自动打开角度(Auto open angle)',
                          '阀前半开L进气(Font half-open L intake*1S)', '阀前半开L测压(Font half-open L Test*1S)',
                          '阀前半开L稳压(Font half-open L Keep*1S)', '阀前半开LΔP1(Font half-open L ΔP1 set*pa)',
                          '阀前半开LΔP2(Font half-open L ΔP2 set*pa)', '阀前全开L进气(Font full-open L intake*1S)',
                          '阀前全开L测压(Font full-open L Test*1S)', '阀前全开L稳压(Font full-open L Keep*1S)',
                          '阀前全开LΔP1(Font full-open L ΔP1 set*pa)', '阀前全开LΔP2(Font full-open L ΔP2 set*pa)',
                          '阀前全开H进气(Font full-open H intake*1S)', '阀前全开H测压(Font full-open H Test*1S)',
                          '阀前全开H稳压(Font full-open H Keep*1S)', '阀前全开HΔP1(Font full-open H ΔP1 set*pa)',
                          '阀前全开HΔP2(Font full-open H ΔP2 set*pa)', '阀后全关H进气(After full-close H intake*1S)',
                          '阀后全关H测压(After full-close H Test*1S)', '阀后全关H稳压(After full-close H Keep*1S)',
                          '阀后全关HΔP1(After full-close H ΔP1 set*pa)', '阀后全关HΔP2(After full-close H ΔP2 set*pa)',
                          '打开转矩(Open torque*N.M)', '关闭转矩(Close torque*N.M)', '排气时间(Exhaust time*1S)',
                          '低压大漏值(Low serious leak value*pa)', '高压大漏值(High serious leak value*pa)',
                          '低压最低压力值(Low minimum pressure*mbar)', '高压最低压力值(High minimum pressure*mbar)', ]
