# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_set.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DataSet(object):
    def setupUi(self, DataSet):
        DataSet.setObjectName("DataSet")
        DataSet.resize(767, 320)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(DataSet)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_data_21 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_21.sizePolicy().hasHeightForWidth())
        self.checkBox_data_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_21.setFont(font)
        self.checkBox_data_21.setObjectName("checkBox_data_21")
        self.verticalLayout.addWidget(self.checkBox_data_21)
        self.checkBox_data_22 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_22.sizePolicy().hasHeightForWidth())
        self.checkBox_data_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_22.setFont(font)
        self.checkBox_data_22.setObjectName("checkBox_data_22")
        self.verticalLayout.addWidget(self.checkBox_data_22)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_data_1 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_1.sizePolicy().hasHeightForWidth())
        self.checkBox_data_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_1.setFont(font)
        self.checkBox_data_1.setObjectName("checkBox_data_1")
        self.gridLayout.addWidget(self.checkBox_data_1, 0, 0, 1, 1)
        self.checkBox_data_2 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_2.sizePolicy().hasHeightForWidth())
        self.checkBox_data_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_2.setFont(font)
        self.checkBox_data_2.setObjectName("checkBox_data_2")
        self.gridLayout.addWidget(self.checkBox_data_2, 0, 1, 1, 1)
        self.checkBox_data_3 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_3.sizePolicy().hasHeightForWidth())
        self.checkBox_data_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_3.setFont(font)
        self.checkBox_data_3.setObjectName("checkBox_data_3")
        self.gridLayout.addWidget(self.checkBox_data_3, 0, 2, 1, 1)
        self.checkBox_data_4 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_4.sizePolicy().hasHeightForWidth())
        self.checkBox_data_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_4.setFont(font)
        self.checkBox_data_4.setObjectName("checkBox_data_4")
        self.gridLayout.addWidget(self.checkBox_data_4, 0, 3, 1, 1)
        self.checkBox_data_5 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_5.sizePolicy().hasHeightForWidth())
        self.checkBox_data_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_5.setFont(font)
        self.checkBox_data_5.setObjectName("checkBox_data_5")
        self.gridLayout.addWidget(self.checkBox_data_5, 0, 4, 1, 1)
        self.checkBox_data_6 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_6.sizePolicy().hasHeightForWidth())
        self.checkBox_data_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_6.setFont(font)
        self.checkBox_data_6.setObjectName("checkBox_data_6")
        self.gridLayout.addWidget(self.checkBox_data_6, 0, 5, 1, 1)
        self.checkBox_data_7 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_7.sizePolicy().hasHeightForWidth())
        self.checkBox_data_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_7.setFont(font)
        self.checkBox_data_7.setObjectName("checkBox_data_7")
        self.gridLayout.addWidget(self.checkBox_data_7, 0, 6, 1, 1)
        self.checkBox_data_8 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_8.sizePolicy().hasHeightForWidth())
        self.checkBox_data_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_8.setFont(font)
        self.checkBox_data_8.setObjectName("checkBox_data_8")
        self.gridLayout.addWidget(self.checkBox_data_8, 0, 7, 1, 1)
        self.checkBox_data_9 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_9.sizePolicy().hasHeightForWidth())
        self.checkBox_data_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_9.setFont(font)
        self.checkBox_data_9.setObjectName("checkBox_data_9")
        self.gridLayout.addWidget(self.checkBox_data_9, 0, 8, 1, 1)
        self.checkBox_data_10 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_10.sizePolicy().hasHeightForWidth())
        self.checkBox_data_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_10.setFont(font)
        self.checkBox_data_10.setObjectName("checkBox_data_10")
        self.gridLayout.addWidget(self.checkBox_data_10, 0, 9, 1, 1)
        self.checkBox_data_11 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_11.sizePolicy().hasHeightForWidth())
        self.checkBox_data_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_11.setFont(font)
        self.checkBox_data_11.setObjectName("checkBox_data_11")
        self.gridLayout.addWidget(self.checkBox_data_11, 1, 0, 1, 1)
        self.checkBox_data_12 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_12.sizePolicy().hasHeightForWidth())
        self.checkBox_data_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_12.setFont(font)
        self.checkBox_data_12.setObjectName("checkBox_data_12")
        self.gridLayout.addWidget(self.checkBox_data_12, 1, 1, 1, 1)
        self.checkBox_data_13 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_13.sizePolicy().hasHeightForWidth())
        self.checkBox_data_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_13.setFont(font)
        self.checkBox_data_13.setObjectName("checkBox_data_13")
        self.gridLayout.addWidget(self.checkBox_data_13, 1, 2, 1, 1)
        self.checkBox_data_14 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_14.sizePolicy().hasHeightForWidth())
        self.checkBox_data_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_14.setFont(font)
        self.checkBox_data_14.setObjectName("checkBox_data_14")
        self.gridLayout.addWidget(self.checkBox_data_14, 1, 3, 1, 1)
        self.checkBox_data_15 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_15.sizePolicy().hasHeightForWidth())
        self.checkBox_data_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_15.setFont(font)
        self.checkBox_data_15.setObjectName("checkBox_data_15")
        self.gridLayout.addWidget(self.checkBox_data_15, 1, 4, 1, 1)
        self.checkBox_data_16 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_16.sizePolicy().hasHeightForWidth())
        self.checkBox_data_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_16.setFont(font)
        self.checkBox_data_16.setObjectName("checkBox_data_16")
        self.gridLayout.addWidget(self.checkBox_data_16, 1, 5, 1, 1)
        self.checkBox_data_17 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_17.sizePolicy().hasHeightForWidth())
        self.checkBox_data_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_17.setFont(font)
        self.checkBox_data_17.setObjectName("checkBox_data_17")
        self.gridLayout.addWidget(self.checkBox_data_17, 1, 6, 1, 1)
        self.checkBox_data_18 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_18.sizePolicy().hasHeightForWidth())
        self.checkBox_data_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_18.setFont(font)
        self.checkBox_data_18.setObjectName("checkBox_data_18")
        self.gridLayout.addWidget(self.checkBox_data_18, 1, 7, 1, 1)
        self.checkBox_data_19 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_19.sizePolicy().hasHeightForWidth())
        self.checkBox_data_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_19.setFont(font)
        self.checkBox_data_19.setObjectName("checkBox_data_19")
        self.gridLayout.addWidget(self.checkBox_data_19, 1, 8, 1, 1)
        self.checkBox_data_20 = QtWidgets.QCheckBox(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_data_20.sizePolicy().hasHeightForWidth())
        self.checkBox_data_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_data_20.setFont(font)
        self.checkBox_data_20.setObjectName("checkBox_data_20")
        self.gridLayout.addWidget(self.checkBox_data_20, 1, 9, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.line_2 = QtWidgets.QFrame(DataSet)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout_108 = QtWidgets.QVBoxLayout()
        self.verticalLayout_108.setObjectName("verticalLayout_108")
        self.horizontalLayout_81 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_81.setObjectName("horizontalLayout_81")
        self.label_2 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_81.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_81.addWidget(self.lineEdit)
        self.label_29 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_81.addWidget(self.label_29)
        self.lineEdit_2 = QtWidgets.QLineEdit(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_81.addWidget(self.lineEdit_2)
        self.label_31 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_81.addWidget(self.label_31)
        self.lineEdit_3 = QtWidgets.QLineEdit(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_81.addWidget(self.lineEdit_3)
        self.label_33 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_81.addWidget(self.label_33)
        self.lineEdit_4 = QtWidgets.QLineEdit(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_81.addWidget(self.lineEdit_4)
        self.label_28 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_81.addWidget(self.label_28)
        self.lineEdit_5 = QtWidgets.QLineEdit(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_81.addWidget(self.lineEdit_5)
        self.label_30 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_81.addWidget(self.label_30)
        self.lineEdit_6 = QtWidgets.QLineEdit(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_81.addWidget(self.lineEdit_6)
        self.label_32 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_81.addWidget(self.label_32)
        self.horizontalLayout_81.setStretch(0, 4)
        self.horizontalLayout_81.setStretch(1, 4)
        self.horizontalLayout_81.setStretch(2, 1)
        self.horizontalLayout_81.setStretch(3, 4)
        self.horizontalLayout_81.setStretch(4, 1)
        self.horizontalLayout_81.setStretch(5, 4)
        self.horizontalLayout_81.setStretch(6, 1)
        self.horizontalLayout_81.setStretch(7, 4)
        self.horizontalLayout_81.setStretch(8, 1)
        self.horizontalLayout_81.setStretch(9, 4)
        self.horizontalLayout_81.setStretch(10, 1)
        self.horizontalLayout_81.setStretch(11, 4)
        self.horizontalLayout_81.setStretch(12, 1)
        self.verticalLayout_108.addLayout(self.horizontalLayout_81)
        self.horizontalLayout_83 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_83.setObjectName("horizontalLayout_83")
        self.label_151 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_151.setFont(font)
        self.label_151.setObjectName("label_151")
        self.horizontalLayout_83.addWidget(self.label_151)
        self.lineEdit_7 = QtWidgets.QLineEdit(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_83.addWidget(self.lineEdit_7)
        self.label_170 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_170.setFont(font)
        self.label_170.setObjectName("label_170")
        self.horizontalLayout_83.addWidget(self.label_170)
        self.lineEdit_8 = QtWidgets.QLineEdit(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_83.addWidget(self.lineEdit_8)
        self.label_171 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_171.setFont(font)
        self.label_171.setObjectName("label_171")
        self.horizontalLayout_83.addWidget(self.label_171)
        self.lineEdit_9 = QtWidgets.QLineEdit(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_83.addWidget(self.lineEdit_9)
        self.label_172 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_172.setFont(font)
        self.label_172.setObjectName("label_172")
        self.horizontalLayout_83.addWidget(self.label_172)
        self.lineEdit_10 = QtWidgets.QLineEdit(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_83.addWidget(self.lineEdit_10)
        self.label_175 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_175.setFont(font)
        self.label_175.setObjectName("label_175")
        self.horizontalLayout_83.addWidget(self.label_175)
        self.lineEdit_11 = QtWidgets.QLineEdit(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_83.addWidget(self.lineEdit_11)
        self.label_176 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_176.setFont(font)
        self.label_176.setObjectName("label_176")
        self.horizontalLayout_83.addWidget(self.label_176)
        self.lineEdit_12 = QtWidgets.QLineEdit(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_83.addWidget(self.lineEdit_12)
        self.label_177 = QtWidgets.QLabel(DataSet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_177.setFont(font)
        self.label_177.setObjectName("label_177")
        self.horizontalLayout_83.addWidget(self.label_177)
        self.horizontalLayout_83.setStretch(0, 4)
        self.horizontalLayout_83.setStretch(1, 4)
        self.horizontalLayout_83.setStretch(2, 1)
        self.horizontalLayout_83.setStretch(3, 4)
        self.horizontalLayout_83.setStretch(4, 1)
        self.horizontalLayout_83.setStretch(5, 4)
        self.horizontalLayout_83.setStretch(6, 1)
        self.horizontalLayout_83.setStretch(7, 4)
        self.horizontalLayout_83.setStretch(8, 1)
        self.horizontalLayout_83.setStretch(9, 4)
        self.horizontalLayout_83.setStretch(10, 1)
        self.horizontalLayout_83.setStretch(11, 4)
        self.horizontalLayout_83.setStretch(12, 1)
        self.verticalLayout_108.addLayout(self.horizontalLayout_83)
        self.verticalLayout_2.addLayout(self.verticalLayout_108)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.line_3 = QtWidgets.QFrame(DataSet)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_data_process_ok = QtWidgets.QPushButton(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_data_process_ok.sizePolicy().hasHeightForWidth())
        self.btn_data_process_ok.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_data_process_ok.setFont(font)
        self.btn_data_process_ok.setStyleSheet("")
        self.btn_data_process_ok.setObjectName("btn_data_process_ok")
        self.horizontalLayout_2.addWidget(self.btn_data_process_ok)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btn_data_process_cancel = QtWidgets.QPushButton(DataSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_data_process_cancel.sizePolicy().hasHeightForWidth())
        self.btn_data_process_cancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_data_process_cancel.setFont(font)
        self.btn_data_process_cancel.setObjectName("btn_data_process_cancel")
        self.horizontalLayout_2.addWidget(self.btn_data_process_cancel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(3, 2)
        self.verticalLayout_2.setStretch(6, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(DataSet)
        QtCore.QMetaObject.connectSlotsByName(DataSet)

    def retranslateUi(self, DataSet):
        _translate = QtCore.QCoreApplication.translate
        DataSet.setWindowTitle(_translate("DataSet", "Form"))
        self.checkBox_data_21.setText(_translate("DataSet", "1-10#"))
        self.checkBox_data_22.setText(_translate("DataSet", "11-20#"))
        self.checkBox_data_1.setText(_translate("DataSet", "1#"))
        self.checkBox_data_2.setText(_translate("DataSet", "2#"))
        self.checkBox_data_3.setText(_translate("DataSet", "3#"))
        self.checkBox_data_4.setText(_translate("DataSet", "4#"))
        self.checkBox_data_5.setText(_translate("DataSet", "5#"))
        self.checkBox_data_6.setText(_translate("DataSet", "6#"))
        self.checkBox_data_7.setText(_translate("DataSet", "7#"))
        self.checkBox_data_8.setText(_translate("DataSet", "8#"))
        self.checkBox_data_9.setText(_translate("DataSet", "9#"))
        self.checkBox_data_10.setText(_translate("DataSet", "10#"))
        self.checkBox_data_11.setText(_translate("DataSet", "11#"))
        self.checkBox_data_12.setText(_translate("DataSet", "12#"))
        self.checkBox_data_13.setText(_translate("DataSet", "13#"))
        self.checkBox_data_14.setText(_translate("DataSet", "14#"))
        self.checkBox_data_15.setText(_translate("DataSet", "15#"))
        self.checkBox_data_16.setText(_translate("DataSet", "16#"))
        self.checkBox_data_17.setText(_translate("DataSet", "17#"))
        self.checkBox_data_18.setText(_translate("DataSet", "18#"))
        self.checkBox_data_19.setText(_translate("DataSet", "19#"))
        self.checkBox_data_20.setText(_translate("DataSet", "20#"))
        self.label_2.setText(_translate("DataSet", "起始时间"))
        self.label_29.setText(_translate("DataSet", "年"))
        self.label_31.setText(_translate("DataSet", "月"))
        self.label_33.setText(_translate("DataSet", "日"))
        self.label_28.setText(_translate("DataSet", "时"))
        self.label_30.setText(_translate("DataSet", "分"))
        self.label_32.setText(_translate("DataSet", "秒"))
        self.label_151.setText(_translate("DataSet", "结束时间"))
        self.label_170.setText(_translate("DataSet", "年"))
        self.label_171.setText(_translate("DataSet", "月"))
        self.label_172.setText(_translate("DataSet", "日"))
        self.label_175.setText(_translate("DataSet", "时"))
        self.label_176.setText(_translate("DataSet", "分"))
        self.label_177.setText(_translate("DataSet", "秒"))
        self.btn_data_process_ok.setText(_translate("DataSet", "确定"))
        self.btn_data_process_cancel.setText(_translate("DataSet", "取消"))

