# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_set.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DataSet(object):
    def setupUi(self, DataSet):
        DataSet.setObjectName("DataSet")
        DataSet.resize(448, 311)
        self.checkBox = QtWidgets.QCheckBox(DataSet)
        self.checkBox.setGeometry(QtCore.QRect(280, 120, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.btn_data_process_ok = QtWidgets.QPushButton(DataSet)
        self.btn_data_process_ok.setGeometry(QtCore.QRect(280, 20, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_data_process_ok.sizePolicy().hasHeightForWidth())
        self.btn_data_process_ok.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_data_process_ok.setFont(font)
        self.btn_data_process_ok.setStyleSheet("")
        self.btn_data_process_ok.setObjectName("btn_data_process_ok")
        self.btn_data_process_cancel = QtWidgets.QPushButton(DataSet)
        self.btn_data_process_cancel.setGeometry(QtCore.QRect(280, 70, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_data_process_cancel.sizePolicy().hasHeightForWidth())
        self.btn_data_process_cancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_data_process_cancel.setFont(font)
        self.btn_data_process_cancel.setObjectName("btn_data_process_cancel")
        self.layoutWidget = QtWidgets.QWidget(DataSet)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 210, 323, 64))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_data_process_1 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_process_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_process_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_data_process_1.setFont(font)
        self.lineEdit_data_process_1.setObjectName("lineEdit_data_process_1")
        self.gridLayout.addWidget(self.lineEdit_data_process_1, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.lineEdit_data_process_2 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_process_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_process_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_data_process_2.setFont(font)
        self.lineEdit_data_process_2.setObjectName("lineEdit_data_process_2")
        self.gridLayout.addWidget(self.lineEdit_data_process_2, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.lineEdit_data_process_3 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_process_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_process_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_data_process_3.setFont(font)
        self.lineEdit_data_process_3.setObjectName("lineEdit_data_process_3")
        self.gridLayout.addWidget(self.lineEdit_data_process_3, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.lineEdit_data_process_4 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_process_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_process_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_data_process_4.setFont(font)
        self.lineEdit_data_process_4.setObjectName("lineEdit_data_process_4")
        self.gridLayout.addWidget(self.lineEdit_data_process_4, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.lineEdit_data_process_5 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_process_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_process_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_data_process_5.setFont(font)
        self.lineEdit_data_process_5.setObjectName("lineEdit_data_process_5")
        self.gridLayout.addWidget(self.lineEdit_data_process_5, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self.lineEdit_data_process_6 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_process_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_process_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_data_process_6.setFont(font)
        self.lineEdit_data_process_6.setObjectName("lineEdit_data_process_6")
        self.gridLayout.addWidget(self.lineEdit_data_process_6, 1, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 5, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setColumnStretch(4, 2)
        self.gridLayout.setColumnStretch(5, 1)
        self.layoutWidget1 = QtWidgets.QWidget(DataSet)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 189, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbtn_data_process_1 = QtWidgets.QRadioButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtn_data_process_1.sizePolicy().hasHeightForWidth())
        self.rbtn_data_process_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rbtn_data_process_1.setFont(font)
        self.rbtn_data_process_1.setObjectName("rbtn_data_process_1")
        self.verticalLayout.addWidget(self.rbtn_data_process_1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbtn_data_process_2 = QtWidgets.QRadioButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtn_data_process_2.sizePolicy().hasHeightForWidth())
        self.rbtn_data_process_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rbtn_data_process_2.setFont(font)
        self.rbtn_data_process_2.setObjectName("rbtn_data_process_2")
        self.horizontalLayout.addWidget(self.rbtn_data_process_2)
        self.lineEdit_data_process_0 = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_process_0.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_process_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_data_process_0.setFont(font)
        self.lineEdit_data_process_0.setObjectName("lineEdit_data_process_0")
        self.horizontalLayout.addWidget(self.lineEdit_data_process_0)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbtn_data_process_3 = QtWidgets.QRadioButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtn_data_process_3.sizePolicy().hasHeightForWidth())
        self.rbtn_data_process_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rbtn_data_process_3.setFont(font)
        self.rbtn_data_process_3.setObjectName("rbtn_data_process_3")
        self.horizontalLayout_2.addWidget(self.rbtn_data_process_3)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.rbtn_data_process_4 = QtWidgets.QRadioButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtn_data_process_4.sizePolicy().hasHeightForWidth())
        self.rbtn_data_process_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rbtn_data_process_4.setFont(font)
        self.rbtn_data_process_4.setObjectName("rbtn_data_process_4")
        self.verticalLayout.addWidget(self.rbtn_data_process_4)

        self.retranslateUi(DataSet)
        QtCore.QMetaObject.connectSlotsByName(DataSet)

    def retranslateUi(self, DataSet):
        _translate = QtCore.QCoreApplication.translate
        DataSet.setWindowTitle(_translate("DataSet", "Form"))
        self.checkBox.setText(_translate("DataSet", "年"))
        self.btn_data_process_ok.setText(_translate("DataSet", "确定"))
        self.btn_data_process_cancel.setText(_translate("DataSet", "取消"))
        self.label.setText(_translate("DataSet", "年"))
        self.label_2.setText(_translate("DataSet", "月"))
        self.label_3.setText(_translate("DataSet", "日"))
        self.label_4.setText(_translate("DataSet", "时"))
        self.label_5.setText(_translate("DataSet", "分"))
        self.label_6.setText(_translate("DataSet", "秒"))
        self.rbtn_data_process_1.setText(_translate("DataSet", "所有存盘数据"))
        self.rbtn_data_process_2.setText(_translate("DataSet", "最近时间"))
        self.label_7.setText(_translate("DataSet", "分"))
        self.rbtn_data_process_3.setText(_translate("DataSet", "固定时间"))
        self.rbtn_data_process_4.setText(_translate("DataSet", "指定时刻的存盘数据"))

