# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_name.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_input_name(object):
    def setupUi(self, input_name):
        input_name.setObjectName("input_name")
        input_name.resize(869, 389)
        self.horizontalLayout = QtWidgets.QHBoxLayout(input_name)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_input_9 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_9.sizePolicy().hasHeightForWidth())
        self.btn_input_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_9.setFont(font)
        self.btn_input_9.setObjectName("btn_input_9")
        self.gridLayout.addWidget(self.btn_input_9, 2, 8, 1, 1)
        self.btn_input_0 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_0.sizePolicy().hasHeightForWidth())
        self.btn_input_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_0.setFont(font)
        self.btn_input_0.setObjectName("btn_input_0")
        self.gridLayout.addWidget(self.btn_input_0, 3, 0, 1, 1)
        self.btn_input_12 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_12.sizePolicy().hasHeightForWidth())
        self.btn_input_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_12.setFont(font)
        self.btn_input_12.setObjectName("btn_input_12")
        self.gridLayout.addWidget(self.btn_input_12, 3, 1, 1, 1)
        self.btn_input_5 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_5.sizePolicy().hasHeightForWidth())
        self.btn_input_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_5.setFont(font)
        self.btn_input_5.setObjectName("btn_input_5")
        self.gridLayout.addWidget(self.btn_input_5, 2, 4, 1, 1)
        self.btn_input_16 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_16.sizePolicy().hasHeightForWidth())
        self.btn_input_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_16.setFont(font)
        self.btn_input_16.setObjectName("btn_input_16")
        self.gridLayout.addWidget(self.btn_input_16, 3, 5, 1, 1)
        self.btn_input_20 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_20.sizePolicy().hasHeightForWidth())
        self.btn_input_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_20.setFont(font)
        self.btn_input_20.setObjectName("btn_input_20")
        self.gridLayout.addWidget(self.btn_input_20, 4, 0, 1, 1)
        self.btn_input_21 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_21.sizePolicy().hasHeightForWidth())
        self.btn_input_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_21.setFont(font)
        self.btn_input_21.setObjectName("btn_input_21")
        self.gridLayout.addWidget(self.btn_input_21, 4, 1, 1, 1)
        self.btn_input_22 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_22.sizePolicy().hasHeightForWidth())
        self.btn_input_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_22.setFont(font)
        self.btn_input_22.setObjectName("btn_input_22")
        self.gridLayout.addWidget(self.btn_input_22, 4, 2, 1, 1)
        self.btn_input_19 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_19.sizePolicy().hasHeightForWidth())
        self.btn_input_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_19.setFont(font)
        self.btn_input_19.setObjectName("btn_input_19")
        self.gridLayout.addWidget(self.btn_input_19, 3, 8, 1, 1)
        self.btn_input_23 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_23.sizePolicy().hasHeightForWidth())
        self.btn_input_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_23.setFont(font)
        self.btn_input_23.setObjectName("btn_input_23")
        self.gridLayout.addWidget(self.btn_input_23, 4, 3, 1, 1)
        self.btn_input_24 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_24.sizePolicy().hasHeightForWidth())
        self.btn_input_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_24.setFont(font)
        self.btn_input_24.setObjectName("btn_input_24")
        self.gridLayout.addWidget(self.btn_input_24, 4, 4, 1, 1)
        self.btn_input_25 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_25.sizePolicy().hasHeightForWidth())
        self.btn_input_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_25.setFont(font)
        self.btn_input_25.setObjectName("btn_input_25")
        self.gridLayout.addWidget(self.btn_input_25, 4, 5, 1, 1)
        self.btn_input_6 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_6.sizePolicy().hasHeightForWidth())
        self.btn_input_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_6.setFont(font)
        self.btn_input_6.setObjectName("btn_input_6")
        self.gridLayout.addWidget(self.btn_input_6, 2, 5, 1, 1)
        self.btn_input_13 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_13.sizePolicy().hasHeightForWidth())
        self.btn_input_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_13.setFont(font)
        self.btn_input_13.setObjectName("btn_input_13")
        self.gridLayout.addWidget(self.btn_input_13, 3, 2, 1, 1)
        self.btn_input_17 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_17.sizePolicy().hasHeightForWidth())
        self.btn_input_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_17.setFont(font)
        self.btn_input_17.setObjectName("btn_input_17")
        self.gridLayout.addWidget(self.btn_input_17, 3, 6, 1, 1)
        self.btn_input_7 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_7.sizePolicy().hasHeightForWidth())
        self.btn_input_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_7.setFont(font)
        self.btn_input_7.setObjectName("btn_input_7")
        self.gridLayout.addWidget(self.btn_input_7, 2, 6, 1, 1)
        self.btn_input_15 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_15.sizePolicy().hasHeightForWidth())
        self.btn_input_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_15.setFont(font)
        self.btn_input_15.setObjectName("btn_input_15")
        self.gridLayout.addWidget(self.btn_input_15, 3, 4, 1, 1)
        self.btn_input_14 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_14.sizePolicy().hasHeightForWidth())
        self.btn_input_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_14.setFont(font)
        self.btn_input_14.setObjectName("btn_input_14")
        self.gridLayout.addWidget(self.btn_input_14, 3, 3, 1, 1)
        self.btn_input_18 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_18.sizePolicy().hasHeightForWidth())
        self.btn_input_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_18.setFont(font)
        self.btn_input_18.setObjectName("btn_input_18")
        self.gridLayout.addWidget(self.btn_input_18, 3, 7, 1, 1)
        self.btn_input_8 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_8.sizePolicy().hasHeightForWidth())
        self.btn_input_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_8.setFont(font)
        self.btn_input_8.setObjectName("btn_input_8")
        self.gridLayout.addWidget(self.btn_input_8, 2, 7, 1, 1)
        self.btn_input_34 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_34.sizePolicy().hasHeightForWidth())
        self.btn_input_34.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_34.setFont(font)
        self.btn_input_34.setObjectName("btn_input_34")
        self.gridLayout.addWidget(self.btn_input_34, 5, 5, 1, 1)
        self.btn_input_35 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_35.sizePolicy().hasHeightForWidth())
        self.btn_input_35.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_35.setFont(font)
        self.btn_input_35.setObjectName("btn_input_35")
        self.gridLayout.addWidget(self.btn_input_35, 5, 6, 1, 1)
        self.btn_input_36 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_36.sizePolicy().hasHeightForWidth())
        self.btn_input_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_36.setFont(font)
        self.btn_input_36.setObjectName("btn_input_36")
        self.gridLayout.addWidget(self.btn_input_36, 5, 7, 1, 1)
        self.btn_input_27 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_27.sizePolicy().hasHeightForWidth())
        self.btn_input_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_27.setFont(font)
        self.btn_input_27.setObjectName("btn_input_27")
        self.gridLayout.addWidget(self.btn_input_27, 4, 7, 1, 1)
        self.btn_input_26 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_26.sizePolicy().hasHeightForWidth())
        self.btn_input_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_26.setFont(font)
        self.btn_input_26.setObjectName("btn_input_26")
        self.gridLayout.addWidget(self.btn_input_26, 4, 6, 1, 1)
        self.btn_input_28 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_28.sizePolicy().hasHeightForWidth())
        self.btn_input_28.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_28.setFont(font)
        self.btn_input_28.setObjectName("btn_input_28")
        self.gridLayout.addWidget(self.btn_input_28, 4, 8, 1, 1)
        self.btn_input_29 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_29.sizePolicy().hasHeightForWidth())
        self.btn_input_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_29.setFont(font)
        self.btn_input_29.setObjectName("btn_input_29")
        self.gridLayout.addWidget(self.btn_input_29, 5, 0, 1, 1)
        self.btn_input_30 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_30.sizePolicy().hasHeightForWidth())
        self.btn_input_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_30.setFont(font)
        self.btn_input_30.setObjectName("btn_input_30")
        self.gridLayout.addWidget(self.btn_input_30, 5, 1, 1, 1)
        self.btn_input_31 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_31.sizePolicy().hasHeightForWidth())
        self.btn_input_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_31.setFont(font)
        self.btn_input_31.setObjectName("btn_input_31")
        self.gridLayout.addWidget(self.btn_input_31, 5, 2, 1, 1)
        self.btn_input_32 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_32.sizePolicy().hasHeightForWidth())
        self.btn_input_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_32.setFont(font)
        self.btn_input_32.setObjectName("btn_input_32")
        self.gridLayout.addWidget(self.btn_input_32, 5, 3, 1, 1)
        self.btn_input_33 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_33.sizePolicy().hasHeightForWidth())
        self.btn_input_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_33.setFont(font)
        self.btn_input_33.setObjectName("btn_input_33")
        self.gridLayout.addWidget(self.btn_input_33, 5, 4, 1, 1)
        self.btn_input_37 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_37.sizePolicy().hasHeightForWidth())
        self.btn_input_37.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_37.setFont(font)
        self.btn_input_37.setObjectName("btn_input_37")
        self.gridLayout.addWidget(self.btn_input_37, 5, 8, 1, 1)
        self.btn_input_cancel = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_cancel.sizePolicy().hasHeightForWidth())
        self.btn_input_cancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_cancel.setFont(font)
        self.btn_input_cancel.setObjectName("btn_input_cancel")
        self.gridLayout.addWidget(self.btn_input_cancel, 1, 7, 1, 2)
        self.btn_input_clear = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_clear.sizePolicy().hasHeightForWidth())
        self.btn_input_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_clear.setFont(font)
        self.btn_input_clear.setObjectName("btn_input_clear")
        self.gridLayout.addWidget(self.btn_input_clear, 1, 1, 1, 1)
        self.btn_input_3 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_3.sizePolicy().hasHeightForWidth())
        self.btn_input_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_3.setFont(font)
        self.btn_input_3.setObjectName("btn_input_3")
        self.gridLayout.addWidget(self.btn_input_3, 2, 2, 1, 1)
        self.btn_input_4 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_4.sizePolicy().hasHeightForWidth())
        self.btn_input_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_4.setFont(font)
        self.btn_input_4.setObjectName("btn_input_4")
        self.gridLayout.addWidget(self.btn_input_4, 2, 3, 1, 1)
        self.btn_input_another = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_another.sizePolicy().hasHeightForWidth())
        self.btn_input_another.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_another.setFont(font)
        self.btn_input_another.setObjectName("btn_input_another")
        self.gridLayout.addWidget(self.btn_input_another, 1, 4, 1, 1)
        self.btn_input_ok = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_ok.sizePolicy().hasHeightForWidth())
        self.btn_input_ok.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_ok.setFont(font)
        self.btn_input_ok.setObjectName("btn_input_ok")
        self.gridLayout.addWidget(self.btn_input_ok, 1, 5, 1, 2)
        self.btn_input_back = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_back.sizePolicy().hasHeightForWidth())
        self.btn_input_back.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_back.setFont(font)
        self.btn_input_back.setObjectName("btn_input_back")
        self.gridLayout.addWidget(self.btn_input_back, 1, 0, 1, 1)
        self.btn_input_1 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_1.sizePolicy().hasHeightForWidth())
        self.btn_input_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_1.setFont(font)
        self.btn_input_1.setObjectName("btn_input_1")
        self.gridLayout.addWidget(self.btn_input_1, 2, 0, 1, 1)
        self.lineEdit_input = QtWidgets.QLineEdit(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_input.sizePolicy().hasHeightForWidth())
        self.lineEdit_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lineEdit_input.setFont(font)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.gridLayout.addWidget(self.lineEdit_input, 0, 0, 1, 9)
        self.btn_input_2 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_2.sizePolicy().hasHeightForWidth())
        self.btn_input_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_2.setFont(font)
        self.btn_input_2.setObjectName("btn_input_2")
        self.gridLayout.addWidget(self.btn_input_2, 2, 1, 1, 1)
        self.btn_input_10 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_10.sizePolicy().hasHeightForWidth())
        self.btn_input_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_10.setFont(font)
        self.btn_input_10.setObjectName("btn_input_10")
        self.gridLayout.addWidget(self.btn_input_10, 1, 3, 1, 1)
        self.btn_input_11 = QtWidgets.QPushButton(input_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_11.sizePolicy().hasHeightForWidth())
        self.btn_input_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_11.setFont(font)
        self.btn_input_11.setObjectName("btn_input_11")
        self.gridLayout.addWidget(self.btn_input_11, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(input_name)
        QtCore.QMetaObject.connectSlotsByName(input_name)

    def retranslateUi(self, input_name):
        _translate = QtCore.QCoreApplication.translate
        input_name.setWindowTitle(_translate("input_name", "输入名字"))
        self.btn_input_9.setText(_translate("input_name", "9"))
        self.btn_input_0.setText(_translate("input_name", "0"))
        self.btn_input_12.setText(_translate("input_name", "A"))
        self.btn_input_5.setText(_translate("input_name", "5"))
        self.btn_input_16.setText(_translate("input_name", "E"))
        self.btn_input_20.setText(_translate("input_name", "I"))
        self.btn_input_21.setText(_translate("input_name", "J"))
        self.btn_input_22.setText(_translate("input_name", "K"))
        self.btn_input_19.setText(_translate("input_name", "H"))
        self.btn_input_23.setText(_translate("input_name", "L"))
        self.btn_input_24.setText(_translate("input_name", "M"))
        self.btn_input_25.setText(_translate("input_name", "N"))
        self.btn_input_6.setText(_translate("input_name", "6"))
        self.btn_input_13.setText(_translate("input_name", "B"))
        self.btn_input_17.setText(_translate("input_name", "F"))
        self.btn_input_7.setText(_translate("input_name", "7"))
        self.btn_input_15.setText(_translate("input_name", "D"))
        self.btn_input_14.setText(_translate("input_name", "C"))
        self.btn_input_18.setText(_translate("input_name", "G"))
        self.btn_input_8.setText(_translate("input_name", "8"))
        self.btn_input_34.setText(_translate("input_name", "W"))
        self.btn_input_35.setText(_translate("input_name", "X"))
        self.btn_input_36.setText(_translate("input_name", "Y"))
        self.btn_input_27.setText(_translate("input_name", "P"))
        self.btn_input_26.setText(_translate("input_name", "O"))
        self.btn_input_28.setText(_translate("input_name", "Q"))
        self.btn_input_29.setText(_translate("input_name", "R"))
        self.btn_input_30.setText(_translate("input_name", "S"))
        self.btn_input_31.setText(_translate("input_name", "T"))
        self.btn_input_32.setText(_translate("input_name", "U"))
        self.btn_input_33.setText(_translate("input_name", "V"))
        self.btn_input_37.setText(_translate("input_name", "Z"))
        self.btn_input_cancel.setText(_translate("input_name", "取消"))
        self.btn_input_clear.setText(_translate("input_name", "清除"))
        self.btn_input_3.setText(_translate("input_name", "3"))
        self.btn_input_4.setText(_translate("input_name", "4"))
        self.btn_input_another.setText(_translate("input_name", "小写"))
        self.btn_input_ok.setText(_translate("input_name", "确定"))
        self.btn_input_back.setText(_translate("input_name", "回退"))
        self.btn_input_1.setText(_translate("input_name", "1"))
        self.btn_input_2.setText(_translate("input_name", "2"))
        self.btn_input_10.setText(_translate("input_name", "_"))
        self.btn_input_11.setText(_translate("input_name", "-"))

