# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_numeric.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InputNumericType(object):
    def setupUi(self, InputNumericType):
        InputNumericType.setObjectName("InputNumericType")
        InputNumericType.setEnabled(True)
        InputNumericType.resize(829, 264)
        self.horizontalLayout = QtWidgets.QHBoxLayout(InputNumericType)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_input_3 = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_3.sizePolicy().hasHeightForWidth())
        self.btn_input_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_3.setFont(font)
        self.btn_input_3.setObjectName("btn_input_3")
        self.gridLayout.addWidget(self.btn_input_3, 1, 3, 1, 1)
        self.btn_input_cancel = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_cancel.sizePolicy().hasHeightForWidth())
        self.btn_input_cancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_cancel.setFont(font)
        self.btn_input_cancel.setObjectName("btn_input_cancel")
        self.gridLayout.addWidget(self.btn_input_cancel, 2, 7, 1, 1)
        self.btn_input_8 = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_8.sizePolicy().hasHeightForWidth())
        self.btn_input_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_8.setFont(font)
        self.btn_input_8.setObjectName("btn_input_8")
        self.gridLayout.addWidget(self.btn_input_8, 2, 3, 1, 1)
        self.btn_input_11 = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_11.sizePolicy().hasHeightForWidth())
        self.btn_input_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_11.setFont(font)
        self.btn_input_11.setObjectName("btn_input_11")
        self.gridLayout.addWidget(self.btn_input_11, 2, 5, 1, 1)
        self.btn_input_clear = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_clear.sizePolicy().hasHeightForWidth())
        self.btn_input_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_clear.setFont(font)
        self.btn_input_clear.setObjectName("btn_input_clear")
        self.gridLayout.addWidget(self.btn_input_clear, 2, 6, 1, 1)
        self.btn_input_7 = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_7.sizePolicy().hasHeightForWidth())
        self.btn_input_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_7.setFont(font)
        self.btn_input_7.setObjectName("btn_input_7")
        self.gridLayout.addWidget(self.btn_input_7, 2, 2, 1, 1)
        self.btn_input_6 = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_6.sizePolicy().hasHeightForWidth())
        self.btn_input_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_6.setFont(font)
        self.btn_input_6.setObjectName("btn_input_6")
        self.gridLayout.addWidget(self.btn_input_6, 2, 1, 1, 1)
        self.lineEdit_input = QtWidgets.QLineEdit(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_input.sizePolicy().hasHeightForWidth())
        self.lineEdit_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lineEdit_input.setFont(font)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.gridLayout.addWidget(self.lineEdit_input, 0, 0, 1, 8)
        self.btn_input_0 = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_0.sizePolicy().hasHeightForWidth())
        self.btn_input_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_0.setFont(font)
        self.btn_input_0.setObjectName("btn_input_0")
        self.gridLayout.addWidget(self.btn_input_0, 1, 0, 1, 1)
        self.btn_input_10 = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_10.sizePolicy().hasHeightForWidth())
        self.btn_input_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_10.setFont(font)
        self.btn_input_10.setObjectName("btn_input_10")
        self.gridLayout.addWidget(self.btn_input_10, 1, 5, 1, 1)
        self.btn_input_ok = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_ok.sizePolicy().hasHeightForWidth())
        self.btn_input_ok.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_ok.setFont(font)
        self.btn_input_ok.setObjectName("btn_input_ok")
        self.gridLayout.addWidget(self.btn_input_ok, 1, 7, 1, 1)
        self.btn_input_5 = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_5.sizePolicy().hasHeightForWidth())
        self.btn_input_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_5.setFont(font)
        self.btn_input_5.setObjectName("btn_input_5")
        self.gridLayout.addWidget(self.btn_input_5, 2, 0, 1, 1)
        self.btn_input_2 = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_2.sizePolicy().hasHeightForWidth())
        self.btn_input_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_2.setFont(font)
        self.btn_input_2.setObjectName("btn_input_2")
        self.gridLayout.addWidget(self.btn_input_2, 1, 2, 1, 1)
        self.btn_input_4 = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_4.sizePolicy().hasHeightForWidth())
        self.btn_input_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_4.setFont(font)
        self.btn_input_4.setObjectName("btn_input_4")
        self.gridLayout.addWidget(self.btn_input_4, 1, 4, 1, 1)
        self.btn_input_back = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_back.sizePolicy().hasHeightForWidth())
        self.btn_input_back.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_back.setFont(font)
        self.btn_input_back.setObjectName("btn_input_back")
        self.gridLayout.addWidget(self.btn_input_back, 1, 6, 1, 1)
        self.btn_input_1 = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_1.sizePolicy().hasHeightForWidth())
        self.btn_input_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_1.setFont(font)
        self.btn_input_1.setObjectName("btn_input_1")
        self.gridLayout.addWidget(self.btn_input_1, 1, 1, 1, 1)
        self.btn_input_9 = QtWidgets.QPushButton(InputNumericType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_9.sizePolicy().hasHeightForWidth())
        self.btn_input_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_input_9.setFont(font)
        self.btn_input_9.setObjectName("btn_input_9")
        self.gridLayout.addWidget(self.btn_input_9, 2, 4, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setColumnStretch(4, 1)
        self.gridLayout.setColumnStretch(5, 1)
        self.gridLayout.setColumnStretch(6, 1)
        self.gridLayout.setColumnStretch(7, 2)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(InputNumericType)
        QtCore.QMetaObject.connectSlotsByName(InputNumericType)

    def retranslateUi(self, InputNumericType):
        _translate = QtCore.QCoreApplication.translate
        InputNumericType.setWindowTitle(_translate("InputNumericType", "数值型"))
        self.btn_input_3.setText(_translate("InputNumericType", "3"))
        self.btn_input_cancel.setText(_translate("InputNumericType", "取消"))
        self.btn_input_8.setText(_translate("InputNumericType", "8"))
        self.btn_input_11.setText(_translate("InputNumericType", "-"))
        self.btn_input_clear.setText(_translate("InputNumericType", "清除"))
        self.btn_input_7.setText(_translate("InputNumericType", "7"))
        self.btn_input_6.setText(_translate("InputNumericType", "6"))
        self.btn_input_0.setText(_translate("InputNumericType", "0"))
        self.btn_input_10.setText(_translate("InputNumericType", "."))
        self.btn_input_ok.setText(_translate("InputNumericType", "确定"))
        self.btn_input_5.setText(_translate("InputNumericType", "5"))
        self.btn_input_2.setText(_translate("InputNumericType", "2"))
        self.btn_input_4.setText(_translate("InputNumericType", "4"))
        self.btn_input_back.setText(_translate("InputNumericType", "回退"))
        self.btn_input_1.setText(_translate("InputNumericType", "1"))
        self.btn_input_9.setText(_translate("InputNumericType", "9"))

