# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'press_set.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PressSet(object):
    def setupUi(self, PressSet):
        PressSet.setObjectName("PressSet")
        PressSet.resize(365, 221)
        self.horizontalLayout = QtWidgets.QHBoxLayout(PressSet)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_47 = QtWidgets.QGridLayout()
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.lab_press_1 = QtWidgets.QLabel(PressSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_press_1.sizePolicy().hasHeightForWidth())
        self.lab_press_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lab_press_1.setFont(font)
        self.lab_press_1.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lab_press_1.setObjectName("lab_press_1")
        self.gridLayout_47.addWidget(self.lab_press_1, 0, 2, 1, 1)
        self.lab_press_2 = QtWidgets.QLabel(PressSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_press_2.sizePolicy().hasHeightForWidth())
        self.lab_press_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lab_press_2.setFont(font)
        self.lab_press_2.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lab_press_2.setObjectName("lab_press_2")
        self.gridLayout_47.addWidget(self.lab_press_2, 1, 2, 1, 1)
        self.lab_press_3 = QtWidgets.QLabel(PressSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_press_3.sizePolicy().hasHeightForWidth())
        self.lab_press_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lab_press_3.setFont(font)
        self.lab_press_3.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lab_press_3.setObjectName("lab_press_3")
        self.gridLayout_47.addWidget(self.lab_press_3, 2, 2, 1, 1)
        self.lineEdit_press_1 = QtWidgets.QLineEdit(PressSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_press_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_press_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_press_1.setFont(font)
        self.lineEdit_press_1.setObjectName("lineEdit_press_1")
        self.gridLayout_47.addWidget(self.lineEdit_press_1, 1, 1, 1, 1)
        self.lab_press1_3 = QtWidgets.QLabel(PressSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_press1_3.sizePolicy().hasHeightForWidth())
        self.lab_press1_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lab_press1_3.setFont(font)
        self.lab_press1_3.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lab_press1_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_press1_3.setObjectName("lab_press1_3")
        self.gridLayout_47.addWidget(self.lab_press1_3, 2, 0, 1, 1)
        self.lab_press1_1 = QtWidgets.QLabel(PressSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_press1_1.sizePolicy().hasHeightForWidth())
        self.lab_press1_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lab_press1_1.setFont(font)
        self.lab_press1_1.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lab_press1_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_press1_1.setObjectName("lab_press1_1")
        self.gridLayout_47.addWidget(self.lab_press1_1, 0, 0, 1, 1)
        self.lab_press1_2 = QtWidgets.QLabel(PressSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_press1_2.sizePolicy().hasHeightForWidth())
        self.lab_press1_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lab_press1_2.setFont(font)
        self.lab_press1_2.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lab_press1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_press1_2.setObjectName("lab_press1_2")
        self.gridLayout_47.addWidget(self.lab_press1_2, 1, 0, 1, 1)
        self.lineEdit_press_2 = QtWidgets.QLineEdit(PressSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_press_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_press_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_press_2.setFont(font)
        self.lineEdit_press_2.setObjectName("lineEdit_press_2")
        self.gridLayout_47.addWidget(self.lineEdit_press_2, 2, 1, 1, 1)
        self.lab_press_show = QtWidgets.QLabel(PressSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_press_show.sizePolicy().hasHeightForWidth())
        self.lab_press_show.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lab_press_show.setFont(font)
        self.lab_press_show.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lab_press_show.setObjectName("lab_press_show")
        self.gridLayout_47.addWidget(self.lab_press_show, 0, 1, 1, 1)
        self.lab_press1_4 = QtWidgets.QLabel(PressSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_press1_4.sizePolicy().hasHeightForWidth())
        self.lab_press1_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lab_press1_4.setFont(font)
        self.lab_press1_4.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lab_press1_4.setText("")
        self.lab_press1_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_press1_4.setObjectName("lab_press1_4")
        self.gridLayout_47.addWidget(self.lab_press1_4, 3, 0, 1, 1)
        self.lineEdit_press_3 = QtWidgets.QLineEdit(PressSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_press_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_press_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_press_3.setFont(font)
        self.lineEdit_press_3.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lineEdit_press_3.setObjectName("lineEdit_press_3")
        self.gridLayout_47.addWidget(self.lineEdit_press_3, 3, 1, 1, 1)
        self.lab_press_4 = QtWidgets.QLabel(PressSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_press_4.sizePolicy().hasHeightForWidth())
        self.lab_press_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lab_press_4.setFont(font)
        self.lab_press_4.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lab_press_4.setText("")
        self.lab_press_4.setObjectName("lab_press_4")
        self.gridLayout_47.addWidget(self.lab_press_4, 3, 2, 1, 1)
        self.gridLayout_47.setColumnStretch(0, 1)
        self.gridLayout_47.setColumnStretch(1, 2)
        self.gridLayout_47.setColumnStretch(2, 1)
        self.gridLayout_47.setRowStretch(0, 1)
        self.gridLayout_47.setRowStretch(1, 1)
        self.gridLayout_47.setRowStretch(2, 1)
        self.gridLayout_47.setRowStretch(3, 1)
        self.horizontalLayout.addLayout(self.gridLayout_47)

        self.retranslateUi(PressSet)
        QtCore.QMetaObject.connectSlotsByName(PressSet)

    def retranslateUi(self, PressSet):
        _translate = QtCore.QCoreApplication.translate
        PressSet.setWindowTitle(_translate("PressSet", "Form"))
        self.lab_press_1.setText(_translate("PressSet", "mbar"))
        self.lab_press_2.setText(_translate("PressSet", "mbar"))
        self.lab_press_3.setText(_translate("PressSet", "mbar"))
        self.lab_press1_3.setText(_translate("PressSet", "量程下限"))
        self.lab_press1_1.setText(_translate("PressSet", "显示值"))
        self.lab_press1_2.setText(_translate("PressSet", "量程上限"))
        self.lab_press_show.setText(_translate("PressSet", "0"))

